services:
  - type: web
    name: menzo-backend-main
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: menzo-db
          property: connectionString
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: "menzo_secret_key_2024_12345"
      - key: ALLOWED_HOSTS
        value: "menzo-backend-main.onrender.com,localhost"
      - key: TELEGRAM_BOT_TOKEN
        value: "8574008500:AAFCSuMbcylAhIeWyXZBMfm-Zv7HcJ-8kVo"
      - key: TELEGRAM_CHAT_ID
        value: "5919683861"
    preDeployCommand: "python manage.py migrate --noinput"

databases:
  - name: menzo-db
    databaseName: menzo_db
    user: menzo_user