# Generated by Django 6.0.4 on 2026-04-20 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('address', models.CharField(max_length=300, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('cuisine', models.CharField(choices=[('Узбекская', 'Узбекская'), ('Итальянская', 'Итальянская'), ('Японская', 'Японская'), ('Китайская', 'Китайская'), ('Европейская', 'Европейская')], max_length=50, verbose_name='Кухня')),
                ('price_level', models.CharField(choices=[('$', '$'), ('$$', '$$'), ('$$$', '$$$')], default='$$', max_length=5, verbose_name='Цены')),
                ('rating', models.FloatField(default=0, verbose_name='Рейтинг')),
                ('working_hours', models.CharField(default='11:00 - 23:00', max_length=200, verbose_name='Часы работы')),
                ('image1', models.URLField(max_length=500, verbose_name='Фото 1')),
                ('image2', models.URLField(blank=True, max_length=500, verbose_name='Фото 2')),
                ('image3', models.URLField(blank=True, max_length=500, verbose_name='Фото 3')),
                ('menu', models.TextField(default='[]', verbose_name='Меню (JSON)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Ресторан',
                'verbose_name_plural': 'Рестораны',
                'ordering': ['-rating'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(max_length=50, unique=True, verbose_name='Номер брони')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('customer_phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time', models.TimeField(verbose_name='Время')),
                ('guests', models.IntegerField(verbose_name='Количество гостей')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждено'), ('cancelled', 'Отменено'), ('completed', 'Завершено')], default='pending', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.restaurant', verbose_name='Ресторан')),
            ],
            options={
                'verbose_name': 'Бронирование',
                'verbose_name_plural': 'Бронирования',
                'ordering': ['-created_at'],
            },
        ),
    ]
