# Generated by Django 5.1.2 on 2026-04-22 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='menu',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='additional_cuisines',
            field=models.CharField(blank=True, help_text='Укажите через запятую: Японская, Китайская, Европейская', max_length=200, verbose_name='Дополнительные кухни'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='telegram',
            field=models.URLField(blank=True, verbose_name='Telegram'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='website',
            field=models.URLField(blank=True, verbose_name='Сайт'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(choices=[('Узбекская', 'Узбекская'), ('Итальянская', 'Итальянская'), ('Японская', 'Японская'), ('Китайская', 'Китайская'), ('Европейская', 'Европейская'), ('Французская', 'Французская'), ('Американская', 'Американская'), ('Индийская', 'Индийская'), ('Корейская', 'Корейская'), ('Вьетнамская', 'Вьетнамская')], max_length=50, verbose_name='Основная кухня'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='price_level',
            field=models.CharField(choices=[('$', 'Эконом (до 50,000 сум)'), ('$$', 'Средний (50,000 - 150,000 сум)'), ('$$$', 'Высокий (150,000 - 300,000 сум)'), ('$$$$', 'Премиум (от 300,000 сум)')], default='$$', max_length=5, verbose_name='Уровень цен'),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название блюда')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена (сум)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu/', verbose_name='Фото блюда')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Рекомендуемое')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='api.restaurant')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Меню',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='restaurants/', verbose_name='Фото')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.restaurant')),
            ],
            options={
                'verbose_name': 'Фото ресторана',
                'verbose_name_plural': 'Фото ресторана',
                'ordering': ['order'],
            },
        ),
    ]
