# Generated by Django 5.1.2 on 2026-04-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_restaurant_image1_remove_restaurant_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Например: 41.311081', max_digits=10, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Например: 69.279562', max_digits=10, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='show_on_map',
            field=models.BooleanField(default=True, verbose_name='Показывать на карте'),
        ),
    ]
