# Generated by Django 5.1.2 on 2026-04-24 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_restaurant_latitude_restaurant_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('family', 'Семейный'), ('romantic', 'Для свиданий'), ('friends', 'С друзьями'), ('business_lunch', 'Бизнес-ланч'), ('kids_friendly', 'С детьми'), ('terrace', 'Терраса'), ('live_music', 'Живая музыка'), ('hookah', 'Кальян'), ('karaoke', 'Караоке'), ('wifi', 'Wi-Fi'), ('parking', 'Парковка'), ('air_conditioning', 'Кондиционер'), ('delivery', 'Доставка'), ('takeaway', 'Самовывоз'), ('online_booking', 'Онлайн-бронирование'), ('open_now', 'Открыто сейчас')], max_length=30, unique=True, verbose_name='Код')),
                ('label', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Особенность',
                'verbose_name_plural': 'Особенности',
                'ordering': ['label'],
            },
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine_type',
            field=models.CharField(choices=[('uzbek', 'Узбекская'), ('european', 'Европейская'), ('italian', 'Итальянская'), ('turkish', 'Турецкая'), ('caucasian', 'Кавказская'), ('asian', 'Азиатская'), ('japanese', 'Японская (суши)'), ('fastfood', 'Бургеры / Фастфуд')], default='uzbek', max_length=20, verbose_name='Тип кухни'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='establishment_type',
            field=models.CharField(choices=[('restaurant', 'Ресторан'), ('cafe', 'Кафе'), ('fastfood', 'Фастфуд'), ('restobar', 'Рестобар'), ('coffeehouse', 'Кофейня'), ('teahouse', 'Чайхана'), ('bakery', 'Пекарня / Кондитерская'), ('canteen', 'Столовая')], default='restaurant', max_length=20, verbose_name='Тип заведения'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cuisine',
            field=models.CharField(blank=True, max_length=50, verbose_name='Основная кухня (текст)'),
        ),
        migrations.CreateModel(
            name='RestaurantFeatureRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_relations', to='api.restaurantfeature')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_relations', to='api.restaurant')),
            ],
            options={
                'verbose_name': 'Особенность ресторана',
                'verbose_name_plural': 'Особенности ресторанов',
                'unique_together': {('restaurant', 'feature')},
            },
        ),
    ]
