# Generated by Django 5.1.2 on 2026-04-25 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_restaurantfeature_restaurant_cuisine_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('icon', models.CharField(default='⭐', max_length=10, verbose_name='Иконка')),
                ('weight', models.FloatField(default=1.0, help_text='От 0 до 2', verbose_name='Вес в общем рейтинге')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Категория оценки',
                'verbose_name_plural': 'Категории оценок',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='booking',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.restaurant'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='additional_cuisines',
            field=models.CharField(blank=True, max_length=200, verbose_name='Дополнительные кухни'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='Долгота'),
        ),
        migrations.CreateModel(
            name='RestaurantAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ratings', models.IntegerField(default=0, verbose_name='Всего оценок')),
                ('unique_raters', models.IntegerField(default=0, verbose_name='Уникальных оценивших')),
                ('food_avg', models.FloatField(default=0, verbose_name='Средняя оценка еды')),
                ('service_avg', models.FloatField(default=0, verbose_name='Средняя оценка обслуживания')),
                ('atmosphere_avg', models.FloatField(default=0, verbose_name='Средняя оценка атмосферы')),
                ('overall_rating', models.FloatField(default=0, verbose_name='Общий рейтинг')),
                ('views_count', models.IntegerField(default=0, verbose_name='Просмотров')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Последнее обновление')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='api.restaurant')),
            ],
            options={
                'verbose_name': 'Аналитика ресторана',
                'verbose_name_plural': 'Аналитика ресторанов',
            },
        ),
        migrations.CreateModel(
            name='RestaurantRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=100, verbose_name='Ключ сессии')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Оценка')),
                ('comment', models.TextField(blank=True, verbose_name='Отзыв')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Подтвержден')),
                ('is_moderated', models.BooleanField(default=False, verbose_name='Промодерирован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.ratingcategory')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.restaurant')),
            ],
            options={
                'verbose_name': 'Оценка ресторана',
                'verbose_name_plural': 'Оценки ресторанов',
                'unique_together': {('restaurant', 'category', 'session_key')},
            },
        ),
    ]
