# Generated by Django 5.1.2 on 2026-04-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ratingcategory_alter_booking_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='region',
            field=models.CharField(choices=[('tashkent', 'Ташкент'), ('tashkent_region', 'Ташкентская область'), ('samarkand', 'Самарканд'), ('bukhara', 'Бухара'), ('khiva', 'Хива'), ('fergana', 'Фергана'), ('andijan', 'Андижан'), ('namangan', 'Наманган'), ('kokand', 'Коканд'), ('nukus', 'Нукус'), ('termiz', 'Термез'), ('qarshi', 'Карши'), ('navoi', 'Навои'), ('jizzakh', 'Джизак'), ('gulistan', 'Гулистан'), ('urgench', 'Ургенч'), ('other', 'Другой город')], db_index=True, default='tashkent', max_length=30, verbose_name='Город/Область'),
        ),
        migrations.AlterField(
            model_name='ratingcategory',
            name='weight',
            field=models.FloatField(default=1.0, verbose_name='Вес в общем рейтинге'),
        ),
    ]
