# Generated by Django 5.1.2 on 2026-05-09 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_restaurant_region_alter_ratingcategory_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['category__order', 'order', 'name'], 'verbose_name': 'Блюдо', 'verbose_name_plural': 'Меню'},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='send_booking_notifications',
            field=models.BooleanField(default=True, verbose_name='Отправлять уведомления о бронированиях'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='send_review_notifications',
            field=models.BooleanField(default=True, verbose_name='Отправлять уведомления об отзывах'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='telegram_bot_token',
            field=models.CharField(blank=True, help_text='Если оставить пустым, будет использоваться основной токен бота', max_length=255, null=True, verbose_name='Токен Telegram бота'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='ID чата в Telegram для отправки уведомлений о бронированиях и отзывах', max_length=100, null=True, verbose_name='Telegram Chat ID для уведомлений'),
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('name_uz', models.CharField(blank=True, max_length=100, verbose_name='Название (Узбекский)')),
                ('name_ru', models.CharField(blank=True, max_length=100, verbose_name='Название (Русский)')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='Название (Английский)')),
                ('icon', models.CharField(blank=True, default='🍽️', max_length=10, verbose_name='Иконка (emoji)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок отображения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='api.restaurant')),
            ],
            options={
                'verbose_name': 'Категория меню',
                'verbose_name_plural': 'Категории меню',
                'ordering': ['order', 'name'],
                'unique_together': {('restaurant', 'name')},
            },
        ),
        migrations.AddField(
            model_name='menuitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='api.menucategory', verbose_name='Категория'),
        ),
    ]
