# Generated by Django 5.1.2 on 2026-05-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, help_text='Загрузите логотип ресторана (круглая иконка)', null=True, upload_to='restaurants/logos/', verbose_name='Логотип ресторана'),
        ),
    ]
