# Generated by Django 5.1.2 on 2026-05-10 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_restaurant_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите фото для категории (будет отображаться в меню)', null=True, upload_to='menu/categories/', verbose_name='Фото категории'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='menu/items/', verbose_name='Фото блюда'),
        ),
    ]
