# Generated by Django 5.1.2 on 2026-05-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantrating',
            name='customer_name',
            field=models.CharField(blank=True, default='Аноним', max_length=100, verbose_name='Имя пользователя'),
        ),
    ]
