# Generated by Django 5.1.2 on 2026-05-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_restaurantrating_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_accepting_bookings',
            field=models.BooleanField(default=False, help_text='Вкл/Выкл приём бронирований через сайт', verbose_name='Принимает бронирования'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_accepting_orders',
            field=models.BooleanField(default=False, help_text='Вкл/Выкл приём заказов через сайт', verbose_name='Принимает заказы'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_gold',
            field=models.BooleanField(default=False, help_text='Премиум статус ресторана (Gold тариф)', verbose_name='Gold ресторан'),
        ),
    ]
