# Generated by Django 5.1.2 on 2026-05-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_restaurant_is_accepting_bookings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_menu_published',
            field=models.BooleanField(default=True, help_text='Отображать меню ресторана. Если снять галочку, страница меню будет недоступна', verbose_name='Меню опубликовано'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Отображать ресторан на сайте. Если снять галочку, ресторан будет скрыт', verbose_name='Опубликован на сайте'),
        ),
    ]
